language: node_js
services:
  - postgresql
env:
  - DATABASE_URL='postgresql://postgres:3201@localhost:5432/fruitdb'
before_script:
  - psql -c 'create database fruitdb;' -U postgres
  - psql -U postgres -d fruitdb -a -f fruits.sql
node_js:
  - 12